ci: invoke cargo update in case of cargo fetch fails

diff --git a/.github/workflows/update-nearcore.yml b/.github/workflows/update-nearcore.yml
--- a/.github/workflows/update-nearcore.yml
+++ b/.github/workflows/update-nearcore.yml
@@ -170,8 +170,11 @@ jobs:
         run: |
           source "$HOME/.cargo/env"
           if ! cargo fetch; then
-            echo "::error::Cargo update failed when updating Cargo.lock"
-            exit 1
+            echo "::warning::Cargo fetch failed, attempting `cargo update`"
+            if ! cargo update; then
+              echo "::error::Cargo update failed when updating Cargo.lock"
+              exit 1
+            fi
           fi
           echo "Updated Cargo.lock"
 
