fix: Updated Cargo.lock, for update-cargo job use cargo update instead of cargo check (#222)
* fix: Updated Cargo.lock, use cargo update instead of cargo check

* fix: build using clang

diff --git a/.github/workflows/update-nearcore.yml b/.github/workflows/update-nearcore.yml
--- a/.github/workflows/update-nearcore.yml
+++ b/.github/workflows/update-nearcore.yml
@@ -169,8 +169,8 @@ jobs:
         id: update_cargo_lock
         run: |
           source "$HOME/.cargo/env"
-          if ! cargo check; then
-            echo "::error::Cargo check failed when updating Cargo.lock"
+          if ! cargo update; then
+            echo "::error::Cargo update failed when updating Cargo.lock"
             exit 1
           fi
           echo "Updated Cargo.lock"
